CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255),
    ATIVO VARCHAR(1)
);

CREATE TABLE COMPRA (
    ID SERIAL PRIMARY KEY,
    IDCLIENTE INTEGER,
    DATACOMPRA DATE,
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(ID)
);


CREATE TABLE PRODUTO (
    ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR (70),
    VALORUNITARIO FLOAT,
    UNIDADE VARCHAR(20)
);


CREATE TABLE ITEMCOMPRA (
    IDPRODUTO INTEGER,
    IDCOMPRA INTEGER,
    QUANTIDADE FLOAT,
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA(ID)
);

